import { useDefaultCameraPosition } from '@/components/Brain/hooks/useCameraPosition'

import { useMediaQuery } from '@/hooks/useMediaQuery'

import type { GetAnnotationsReturn } from './types'

export const useAnnotations: (() => GetAnnotationsReturn) = () => {
  const { isGteTablet } = useMediaQuery()

  const defaultCameraPosition = useDefaultCameraPosition()

  return [
    {
      label: 'Hi 👋',
      id: 'autoShow',
      // isAutoShow: true,
      position: [ 0.2, isGteTablet ? -0.15 : -0.135, 0.4 ],
      size: isGteTablet ? 0.0175 : 0.025,
      fontSize: isGteTablet ? 0.01 : 0.015,
      expandedPosition: [ 0, 0, 1 ],
      expandedScale: isGteTablet ? 15 : 13,
      expandedCameraPosition: defaultCameraPosition,
      content: `Hi, I'm Matt Rabe.\n\nTake a look around at\nsome of the things on my mind.`,
    },
    {
      label: 'About',
      position: [ 0.2, -0.2, 0.4 ],
      size: isGteTablet ? 0.0175 : 0.025,
      fontSize: isGteTablet ? 0.01 : 0.015,
      expandedPosition: [ 0, 0, 1 ],
      expandedScale: isGteTablet ? 14 : 13.5,
      expandedFontSize: isGteTablet ? 0.009 : 0.013,
      expandedCameraPosition: [ 0, 0, 2.5 ],
      content: `I built this 3D interface using\nReact Three Fiber+React Three Drei.\n\nI had never used those tools before\nand it was a fun challenge.\n\nSource is available on Github\n(https://github.com/mattrabe/mattrabe.com).\n\nThe brain model is the lovely "Brain Areas"\nmodel by Versal (https://skfb.ly/AFry)\nand is licensed under\nCreative Commons Attribution 4.0.\n`,
    },

    {
      label: 'TypeScript',
      position: [ 0.1, 0.1, 0.7 ],
      size: 0.055,
      expandedPosition: [ 0, 0, 1 ],
      expandedScale: isGteTablet ? 5 : 5,
      expandedCameraPosition: [ 0, 0, 2.25 ],
      expandedFontSize: isGteTablet ? 0.01 : 0.0105,
      content: `I'm a big fan of TypeScript.\n\nType safety in general just makes me happy.\nAnd end-to-end type safety - what a concept!\nE2ETS gives me a thrill,\nand complex generic types satisfy me.\n\nI've been working professionally with TypeScript for\nmany years and have worked more projects\nusing it than I even wish to count!\n\n`,
    },
    {
      label: 'node.js',
      position: [ 0.125, 0.225, 0.675 ],
      size: 0.03,
      fontSize: 0.015,
      expandedPosition: [ 0.125, 0.225, 0.75 ],
      expandedScale: 9.5,
      expandedCameraPosition: [ 0.33, 0.5, 2 ],
      expandedFontSize: 0.0115,
      content: `\nnode.js is the foundation on which most of\nthe backend and scripting work I have done\nover the past 5 years rests.\n\nI still remember when it first came out.\nFast forward 10 years and we were writing\nbackends in the same language as\nour web and native client apps.`,
    },
    {
      label: 'Express.js',
      position: [ 0.14, 0.325, 0.6 ],
      size: 0.04,
      fontSize: 0.015,
      expandedPosition: [ 0.35, 0.325, 0.7 ],
      expandedScale: 9,
      expandedCameraPosition: [ 1, 0.75, 2 ],
      expandedFontSize: 0.02,
      content: `\nI love a nice lightweight and\nunopinionated framework.\n\nExpress stays out of the way,\nallowing the developer to build\nbusiness logic and source tools\nfrom separate, dedicated\nlibraries.`
    },
    {
      label: 'SQL',
      position: [ 0.4, 0.035, 0.305 ],
      size: 0.03,
    },
    {
      label: 'AWS',
      position: [ 0.225, 0.175, 0.635 ],
      size: 0.03,
      expandedPosition: [ 0.375, 0.175, 0.6 ],
      expandedCameraPosition: [ 1.245, 0.225, 2 ],
      content: `AWS Copilot for automation.\nECS and EKS for containers.\nEC2 for compute.\nS3 for storage and static hosting.\nLambda for serverless functions.\nSecrets Manager for secrets.\nRDS for relational data.`,
    },
    {
      label: 'Docker',
      position: [ 0.2575, 0.3, 0.5 ],
      size: 0.035,
      fontSize: 0.0175,
    },
    {
      label: 'CI/CD',
      position: [ 0.1, 0, 0.65 ],
      size: 0.03,
      fontSize: 0.015,
      expandedPosition: [ 0.1, 0, 0.75 ],
      expandedCameraPosition: [ 0.28, 0, 2.1 ],
      expandedScale: isGteTablet ? 10 : 10,
      content: `\nI've spent a considerable amount\nof time on CI/CD pipeline\nautomation recently.\n\nI really enjoy providing excellent\ntooling to developers. Watching\nproductivity go up and\ncomplaints go down is\nthe reward.`,
    },
    {
      label: 'REST',
      position: [ 0.325, 0.275, 0.36 ],
      size: 0.03,
    },
    {
      label: 'AI & LLM',
      position: [ -0.1, 0.35, 0.595 ],
      size: 0.05,
      expandedPosition: [ -0.1, 0.35, 0.65 ],
      expandedCameraPosition: [ -0.35, 1, 2.1 ],
      expandedScale: 7,
      expandedFontSize: 0.0175,
      content: `Vibe coding, agentic IDEs,\nusing AI to write more tests in\nless time than I ever could,\nmaking AI write code in\nlanguages I don't know,\nCursor instead of VSCode,\nGithub Copilot, OpenAI, Anthropic,\nAmazon Rekognition, LangChain,\n RAG, chatbots, using AI to\nfix slippery bugs.`,
    },
    {
      label: 'React',
      position: [ 0.05, 0.25, 0.65 ],
      size: 0.04,
      expandedPosition: [ 0.05, 0.25, 0.7 ],
      expandedScale: 7.5,
      expandedCameraPosition: [ 0.15, 0.5, 2 ],
      expandedFontSize: 0.015,
      content: `\nThis site was built using React.\nI've built a lot of things with React.\n\nThe JS/TS stack is just so versatile\nthese days, and React gives us\na common foundation on which\nwe can build interfaces that\nrun just about anywhere.`,
    },
    {
      label: `React\nNative`,
      position: [ 0, 0.325, 0.6 ],
      size: 0.05,
      expandedPosition: [ 0, 0.325, 0.7 ],
      expandedScale: 6.5,
      expandedCameraPosition: [ 0, 0.9, 2 ],
      expandedFontSize: 0.0125,
      content: `\nReact Native really ties the room together\nwhen it comes to the MERN stack.\n\nOh how I love being able to implement\nend to end type safety between the backend\nand both native and browser clients.\n\nOh how I love being able to share components\nbetween native and web.\n\nI was a react-native-web early adopter,\nand I have no regrets.`
    },
    {
      label: 'Vue.js',
      position: [ -0.335, 0.315, 0.3 ],
      size: 0.03,
      fontSize: 0.0175,
    },
    {
      label: 'Angular',
      position: [ -0.375, 0.3, 0.225 ],
      size: 0.0375,
      fontSize: 0.0175,
    },
    {
      label: 'PHP',
      position: [ 0.2, 0.05, -0.625 ],
      size: 0.03,
    },
    {
      label: 'Laravel',
      position: [ 0.22, 0.15, -0.6 ],
      size: 0.04,
    },
    {
      label: 'FilamentPHP',
      position: [ 0.1, 0.2, -0.625 ],
      size: 0.05,
      fontSize: 0.015,
    },
    {
      label: 'Problem\nSolving',
      position: [ 0.275, 0.05, 0.625 ],
      size: 0.055,
      expandedScale: 7,
      expandedPosition: [ 0.485, 0.05, 0.65 ],
      expandedCameraPosition: [ 1.5, 0.05, 2 ],
      content: `A fundamental skill of developers,\nengineers, leaders, and business\npeople. Also comes in handy if\nyour car breaks down.`,
    },
    {
      label: 'Aneurysm',
      position: [ 0, 0, 0.525 ],
      size: 0.025,
      fontSize: 0.0095,
      expandedPosition: [ 0, 0, 1 ],
      expandedFontSize: 0.0125,
      content: `I am an aneurysm survivor.\n7/31/2016.\n\nLook up "Circle of Willis" to see how the\nhuman brain implements critical redundancy.\n\nGo get your brain scanned - don't wait!\nYour family loves you!`,
    },
    {
      label: 'Music',
      position: [ -0.2, 0.15, 0.65 ],
      size: 0.05,
      expandedPosition: [ -0.2, 0.15, 1 ],
      expandedScale: 4.5,
      expandedCameraPosition: [ -0.4, 0.15, 2 ],
      expandedFontSize: 0.015,
      content: `My first and longest\nrunning love.`,
    },
    {
      label: 'Guitar',
      position: [ -0.15, 0.05, 0.66 ],
      size: 0.0325,
      fontSize: 0.015,
      expandedPosition: [ -0.15, 0.05, 0.8 ],
      expandedScale: 7,
      expandedFontSize: 0.0125,
      expandedCameraPosition: [ -0.4, 0.1, 2 ],
      content: `\nI wail. Though these days you're\nmore likely to find me strumming\naround a campfire or jamming\nwith my son than shredding\non a stage.`,
    },
    {
      label: 'Drums',
      position: [ -0.29, 0.12, 0.58 ],
      size: 0.0305,
      fontSize: 0.016,
      expandedPosition: [ -0.35, 0.15, 1 ],
      expandedScale: isGteTablet ? 10 : 8,
      expandedFontSize: isGteTablet ? 0.015 : 0.0125,
      expandedCameraPosition: [ -0.7, 0.25, 2 ],
      content: `\nYou can find me on stage playing drums.\nYet another form of mathematical\nmusical expression.`,
    },
    {
      label: 'Vocals',
      position: [ -0.125, 0.225, 0.655 ],
      size: 0.0325,
      fontSize: 0.015,
      expandedPosition: [ -0.225, 0.2, 1 ],
      expandedScale: isGteTablet ? 10 : 11,
      expandedCameraPosition: [ -0.55, 0.4, 2.5 ],
      expandedFontSize: isGteTablet ? 0.015 : 0.0165,
      content: `\nYea I can sing the hell out of a tune.\n\nBut my all time favorite musical instrument\nto perform with is vocal harmonies.\n\nThere's just nothing quite like nailing\na 3 or 5, feeling the sound fill out,\nand knowing that the audience\nmight not even know.`,
    },

    {
      label: 'Woodworking',
      position: [ -0.225, -0.075, 0.45 ],
      size: 0.055,
      fontSize: 0.014,
      expandedPosition: [ -0.225, -0.075, 1 ],
      expandedScale: isGteTablet ? 7 : 6,
      expandedCameraPosition: [ -0.55, -0.2, 2.5 ],
      expandedFontSize: isGteTablet ? 0.015 : 0.0135,
      content: `I've been spending free time woodworking\nas a hobby since late 2024. I've been\nmostly building boxes and inlays.\n\nI immediately fell in love with the combination of\nproblem solving, small engineering challenges,\nbeing "in the zone" artistically, and creating\nbeatiful objects that I can hold in my hand\nand give away as gifts.`,
    },
  ]
}
